// <auto-generated />
using System;
using Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Data.Migrations
{
    [DbContext(typeof(ITIDbContext))]
    [Migration("20250210112959_AddDBITI2")]
    partial class AddDBITI2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Data.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1000L);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Top_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Top_id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Assignment.Data.Models.Course_Ins", b =>
                {
                    b.Property<int>("Inst_id")
                        .HasColumnType("int");

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<int>("Evaluate")
                        .HasColumnType("int");

                    b.HasKey("Inst_id", "Course_id");

                    b.HasIndex("Course_id");

                    b.ToTable("Course_Ins");
                });

            modelBuilder.Entity("Assignment.Data.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 10L, 10);

                    b.Property<DateOnly>("Hiring_Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Ins_id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.HasKey("ID");

                    b.HasIndex("Ins_id")
                        .IsUnique();

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Assignment.Data.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Bouns")
                        .HasColumnType("decimal");

                    b.Property<int?>("DepartmenttID")
                        .HasColumnType("int");

                    b.Property<int>("Dept_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Hour_Rate")
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasMaxLength(6)
                        .HasColumnType("decimal");

                    b.HasKey("ID");

                    b.HasIndex("DepartmenttID");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("Assignment.Data.Models.Std_Courses", b =>
                {
                    b.Property<int>("Stud_id")
                        .HasColumnType("int");

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<int>("Grarde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Stud_id", "Course_id");

                    b.HasIndex("Course_id");

                    b.ToTable("Std_Course");
                });

            modelBuilder.Entity("Assignment.Data.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 102L);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Dep_id")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("ID");

                    b.HasIndex("Dep_id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Assignment.Data.Models.Topic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 200L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("Assignment.Data.Models.Course", b =>
                {
                    b.HasOne("Assignment.Data.Models.Topic", "HasTopic")
                        .WithMany("Topicc")
                        .HasForeignKey("Top_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HasTopic");
                });

            modelBuilder.Entity("Assignment.Data.Models.Course_Ins", b =>
                {
                    b.HasOne("Assignment.Data.Models.Course", "Course2")
                        .WithMany("Courses_Ins")
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Data.Models.Instructor", "Instructor2")
                        .WithMany("Instructors")
                        .HasForeignKey("Inst_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course2");

                    b.Navigation("Instructor2");
                });

            modelBuilder.Entity("Assignment.Data.Models.Department", b =>
                {
                    b.HasOne("Assignment.Data.Models.Instructor", "Instruct")
                        .WithOne("Exist")
                        .HasForeignKey("Assignment.Data.Models.Department", "Ins_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruct");
                });

            modelBuilder.Entity("Assignment.Data.Models.Instructor", b =>
                {
                    b.HasOne("Assignment.Data.Models.Department", "Departmentt")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmenttID");

                    b.Navigation("Departmentt");
                });

            modelBuilder.Entity("Assignment.Data.Models.Std_Courses", b =>
                {
                    b.HasOne("Assignment.Data.Models.Course", "Cou_rse")
                        .WithMany("Courses")
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Data.Models.Student", "Stu_dent")
                        .WithMany("Courses")
                        .HasForeignKey("Stud_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cou_rse");

                    b.Navigation("Stu_dent");
                });

            modelBuilder.Entity("Assignment.Data.Models.Student", b =>
                {
                    b.HasOne("Assignment.Data.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("Dep_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Assignment.Data.Models.Course", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Courses_Ins");
                });

            modelBuilder.Entity("Assignment.Data.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Assignment.Data.Models.Instructor", b =>
                {
                    b.Navigation("Exist");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Assignment.Data.Models.Student", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Assignment.Data.Models.Topic", b =>
                {
                    b.Navigation("Topicc");
                });
#pragma warning restore 612, 618
        }
    }
}
